Pages/Cadastro.cshtml.cs
using AgroConnect.Data;
using AgroConnect.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class CadastroModel : PageModel
    {
        private readonly AgroConnectDbContext _context;

        public CadastroModel(AgroConnectDbContext context)
        {
            _context = context;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Usuario Usuarios { get; set; }
        public async Task<IActionResult> OnPost() 
        {
            if(_context.usuarios == null || Usuarios == null)
            {
                return Page();
            }
            _context.usuarios.Add(Usuarios);
            await _context.SaveChangesAsync();

            return RedirectToPage("Login");
        }
    }
}

Pages/Deslogar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class DeslogarModel : PageModel
    {
        public IActionResult OnGet()
        {
            ClearIdCookie();

            return RedirectToPage("Index");
        }

        public void ClearIdCookie()
        {
            if (Request.Cookies.ContainsKey("UsuarioLogado"))
            {
                Response.Cookies.Delete("UsuarioLogado");
            }
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AgroConnect.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/GadoHome.cshtml.cs
using AgroConnect.Data;
using AgroConnect.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AgroConnect.Pages
{
    public class GadoHomeModel : PageModel
    {
        private readonly AgroConnectDbContext _context;

        private int? _idUsuarioLogado;
        public GadoHomeModel(AgroConnectDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<Gado> GadosFront { get; set; }

        [BindProperty]
        public Gado GadoCadastro { get; set; }

        [BindProperty]
        public Gado GadoEditar { get; set; }

        [BindProperty]
        public Gado GadoDeletar { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            GetCookieIdUsuarioLogado();

            if (_idUsuarioLogado == null)
            {
                return RedirectToPage("/Error");
            }

            GadosFront = await _context.gados.Where(x => x.UsuarioId == _idUsuarioLogado).OrderBy(x => x.Id).ToListAsync();

            GadosFront.ForEach(x =>
            {
                if (x.Historico == null && x.HistoricoId == null)
                {
                    x.Historico = new GadoHistorico() { Reproducao = "", Saude = "", Vacina = "" };
                }
                else
                {
                    x.Historico = _context.gadoHistoricos.Find(x.HistoricoId);
                }
            });

            return Page();
        }

        [HttpPost]
        public async Task<IActionResult> OnPostCreate()
        {
            GetCookieIdUsuarioLogado();
            GadoCadastro.UsuarioId = _idUsuarioLogado.Value;

            if(GadoCadastro.Historico == null)
            {
                GadoCadastro.Historico = new GadoHistorico() { Reproducao = "", Saude = "", Vacina = "" };
            }

            _context.gadoHistoricos.Add(GadoCadastro.Historico);
            await _context.SaveChangesAsync();
            GadoCadastro.Historico = await _context.gadoHistoricos.OrderByDescending(gh => gh.Id).FirstOrDefaultAsync();

            _context.gados.Add(GadoCadastro);
            await _context.SaveChangesAsync();
            return RedirectToAction("OnGetAsync");
        }

        [HttpPost]
        public async Task<IActionResult> OnPostUpdate()
        {
            GetCookieIdUsuarioLogado();
            GadoEditar.UsuarioId = _idUsuarioLogado.Value;

            if (GadoEditar.Historico == null)
            {
                GadoEditar.Historico = new GadoHistorico() { Reproducao = "", Saude = "", Vacina = "" };
            }

            _context.gadoHistoricos.Update(GadoEditar.Historico);
            await _context.SaveChangesAsync();

            _context.gados.Update(GadoEditar);
            await _context.SaveChangesAsync();
            return RedirectToAction("OnGetAsync");
        }

        [HttpPost]
        public async Task<IActionResult> OnPostDelete()
        {
            GetCookieIdUsuarioLogado();
            GadoDeletar.UsuarioId = _idUsuarioLogado.Value;

            var historicoId = await _context.gados.Where(x => x.Id == GadoDeletar.Id).Select(x => x.HistoricoId).FirstOrDefaultAsync();
            var historico = await _context.gadoHistoricos.FindAsync(historicoId);

            _context.gadoHistoricos.Remove(historico);
            await _context.SaveChangesAsync();
            return RedirectToAction("OnGetAsync");
        }

        private void GetCookieIdUsuarioLogado()
        {
            var cookie = Request.Cookies["UsuarioLogado"];
            _idUsuarioLogado = cookie == null ? null : int.Parse(cookie);
        }
    }
}

Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class HomeModel : PageModel
    {
        private int? _idUsuarioLogado;

        public IActionResult OnGet()
        {
            GetCookieIdUsuarioLogado();

            if (_idUsuarioLogado == null)
            {
                return RedirectToPage("/Error");
            }

            return Page();

        }

        private void GetCookieIdUsuarioLogado()
        {
            var cookie = Request.Cookies["UsuarioLogado"];
            _idUsuarioLogado = cookie == null ? null : int.Parse(cookie);
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Login.cshtml.cs
using AgroConnect.Data;
using AgroConnect.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AgroConnect.Pages
{
    public class LoginModel : PageModel
    {
        private readonly AgroConnectDbContext _context;

        public LoginModel(AgroConnectDbContext context)
        {
            _context = context;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Usuario UsuarioFront { get; set; }
        public async Task<IActionResult> OnPost()
        {
            if (_context.usuarios == null || UsuarioFront == null)
            {
                return Page();
            }

            List<Usuario> Comparar = await _context.usuarios.ToListAsync();

            bool Acesso = Comparar.Any(x => UsuarioFront.Email == x.Email && UsuarioFront.Senha == x.Senha);

            if (Acesso)
            {
                Usuario usuarioLogando = await _context.usuarios.FirstOrDefaultAsync(NomeIgual => (NomeIgual.Email == UsuarioFront.Email && UsuarioFront.Senha == NomeIgual.Senha));

                // Put the id of the logged user on a cookie for future use

                SetIdCookie(usuarioLogando.Id);

                return RedirectToPage("Home");
            }
            else
            {
                return RedirectToPage("Login");
            }
        }

        public void SetIdCookie(int id)
        {
            Response.Cookies.Append("UsuarioLogado", id.ToString());
        }
        
    }
}

Pages/PlantacoesEditar.cshtml.cs
using AgroConnect.Data;
using AgroConnect.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class PlantacoesEditarModel : PageModel
    {
        private readonly AgroConnectDbContext _context;

        public PlantacoesEditarModel(AgroConnectDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Plantacao PlantacoesFront { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            if (!TempData.ContainsKey("UsuarioLogado"))
            {
                return RedirectToPage("/Error");
            }

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            _context.plantacoes.Add(PlantacoesFront);
            await _context.SaveChangesAsync();
            return RedirectToPage("PlantacoesHome");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgroConnect.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/Cadastro.cshtml
@page
@model AgroConnect.Pages.CadastroModel
@{
}

<style>
    /* Estilos personalizados */
    .bg-image {
        background-image: url("~/images/LavouraSoja.jpg"); /* Substitua pelo caminho correto da imagem de fundo */
      background-size: cover;
      background-position: center;
      height: 100vh;
    }
    /* Estilos para o formulário */
    .form-container {
      background-color: rgba(255, 255, 255, 0.9);
      padding: 20px;
      border-radius: 10px;
    }
  </style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 p-5 form-container">
            <h2>Cadastre-se Aqui</h2>
            <form method="post">
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input asp-for="Usuarios.Nome" type="text" class="form-control" id="nome" placeholder="Digite seu nome completo">
                </div>
                <div class="form-group">
                    <label for="cpf">CPF:</label>
                    <input asp-for="Usuarios.Cpf" type="text" class="form-control" id="cpf" placeholder="Digite seu cpf completo">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input asp-for="Usuarios.Email" type="email" class="form-control" id="email" placeholder="Digite seu email">
                </div>
                <div class="form-group">
                    <label for="senha">Senha:</label>
                    <input asp-for="Usuarios.Senha" type="password" class="form-control" id="senha" placeholder="Digite sua senha">
                </div>
                <div class="form-group">
                    <label for="cidade">Cidade:</label>
                    <input asp-for="Usuarios.Cidade"  type="text" class="form-control" id="cidade" placeholder="Digite sua cidade">
                </div>
                <div class="form-group">
                    <label for="telefone">Telefone:</label>
                    <input asp-for="Usuarios.Telefone" type="tel" class="form-control" id="telefone" placeholder="Digite seu telefone">
                </div>
                <button type="submit" value="Usuario" class="btn btn-primary">Registrar</button>
                <button type="button" class="btn btn-outline-danger">Registrar com Google</button>
            </form>
        </div>
        <div class="col-md-6 bg-image">
            <img src="~/images/LavouraSoja.jpg" class="w-100 h-auto object-fit-fill" alt="img">
        </div>
    </div>
</div>

Pages/Deslogar.cshtml
@page
@model AgroConnect.Pages.DeslogarModel
@{
}

<h3>Deslogando...</h3>

Pages/GadoHome.cshtml
@page "/Gado"
@model AgroConnect.Pages.GadoHomeModel
@{
}


<div class="container-fluid px-5">
    <div class="row px-0">
        <!-- Cabeçalho do conteúdo principal -->
        <h1>Gados</h1>

        <!-- Cards com dados -->
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dados 1</h5>
                        <p class="card-text">Informações relevantes aqui.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dados 2</h5>
                        <p class="card-text">Outras informações importantes.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dados 3</h5>
                        <p class="card-text">Mais detalhes relevantes.</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Botão de adicionar lavoura -->
        <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#createModal">Adicionar Gado</button>

        <!-- Barra de pesquisa -->
        <div class="input-group mt-3">
            <input type="text" class="form-control" id="searchInput" placeholder="Pesquisar...">
            <button class="btn btn-outline-secondary" type="button">Buscar</button>
        </div>

        <!-- Tabela -->
        <table class="table table-striped table-hover mt-3" id="gadosTable">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Id)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Nome)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Raca)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Peso)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Historico.Saude)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Historico.Reproducao)</th>
                    <th>@Html.DisplayNameFor(model => model.GadosFront[0].Historico.Vacina)</th>
                    <th>Ações</th>

                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.GadosFront.Any())
                {
                    @foreach (var gado in Model.GadosFront)
                    {
                        <tr>
                            <th>@gado.Id</th>
                            <th>@gado.Nome</th>
                            <th>@gado.Raca</th>
                            <th>@gado.Peso</th>
                            <th>@gado.Historico.Saude</th>
                            <th>@gado.Historico.Reproducao</th>
                            <th>@gado.Historico.Vacina</th>
                            <th class="d-flex">
                                <button type="button" class="btn btn-primary px-4 me-3" data-bs-toggle="modal" data-bs-target="#editModal-@gado.Id">
                                    Editar
                                </button>

                                <form method="post" asp-page="GadoHome" asp-page-handler="Delete">
                                    <input type="text" hidden="hidden" asp-for="GadoDeletar.Id" value="@gado.Id" />
                                    <button type="submit" class="btn btn-danger px-4">Deletar</button>
                                </form>

                                <div class="modal fade" id="editModal-@gado.Id" tabindex="-1" role="dialog" aria-labelledby="editModalLabel-@gado.Id" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="editModalLabel-@gado.Id">Editar Gado</h5>
                                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Fechar">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form method="post" asp-page="GadoHome" asp-page-handler="Update">
                                                    <!-- Formulário com os campos para edição -->
                                                    <input type="text" hidden="hidden" asp-for="GadoEditar.Id" value="@gado.Id" />
                                                    <div class="form-group">
                                                        <label for="nomePropriedade">Nome:</label>
                                                        <input type="text" class="form-control" id="editNome" asp-for="GadoEditar.Nome" value="@gado.Nome">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="tipoGado">Raca:</label>
                                                        <input type="text" class="form-control" id="editTipoGado" asp-for="GadoEditar.Raca" value="@gado.Raca">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="quantidade">Peso:</label>
                                                        <input type="number" class="form-control" id="editQuantidade" asp-for="GadoEditar.Peso" value="@gado.Peso">
                                                    </div>
                                                    <hr />
                                                    <h5>Histórico do Gado:</h5>
                                                    <input type="text" hidden="hidden" asp-for="GadoEditar.Historico.Id" value="@gado.Historico.Id" />
                                                    <div class="form-group">
                                                        <label for="">Saúde:</label>
                                                        <input type="text" class="form-control" id="editHistoricoSaude" asp-for="GadoEditar.Historico.Saude" value="@gado.Historico.Saude">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="dataColheita">Reprodução:</label>
                                                        <input type="text" class="form-control" id="editHistoricoReproducao" asp-for="GadoEditar.Historico.Reproducao" value="@gado.Historico.Reproducao">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="dataColheita">Vacina:</label>
                                                        <input type="text" class="form-control" id="editHistoricoVacina" asp-for="GadoEditar.Historico.Vacina" value="@gado.Historico.Vacina">
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                                                        <button type="submit" class="btn btn-primary">Salvar mudanças</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </th>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="8" class="text-center">
                            Nenhum gado cadastrada no sistema.
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createexamModalLabel">Cadastrar Gado</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-page="GadoHome" asp-page-handler="Create">
                    <div class="form-group">
                        <label for="nomePropriedade">Nome da Propriedade:</label>
                        <input type="text" class="form-control" id="nomePropriedade" asp-for="GadoCadastro.Nome" placeholder="Nome">
                    </div>
                    <div class="form-group">
                        <label for="tipoGado">Tipo de Plantação:</label>
                        <input type="text" class="form-control" id="tipoGado" asp-for="GadoCadastro.Raca" placeholder="Raça">
                    </div>
                    <div class="form-group">
                        <label for="quantidade">Quantidade:</label>
                        <input type="number" class="form-control" id="quantidade" asp-for="GadoCadastro.Peso" placeholder="Peso">
                    </div>
                    <hr />
                    <h5>Histórico do Gado:</h5>
                    <div class="form-group">
                        <label for="historico">Saúde:</label>
                        <input type="text" class="form-control" id="historicoSaude" asp-for="GadoCadastro.Historico.Saude" placeholder="Saúde">
                    </div>
                    <div class="form-group">
                        <label for="historico">Reprodução:</label>
                        <input type="text" class="form-control" id="historicoReproducao" asp-for="GadoCadastro.Historico.Reproducao" placeholder="Reprodução">
                    </div>
                    <div class="form-group">
                        <label for="historico">Vacina:</label>
                        <input type="text" class="form-control" id="historicoVacina" asp-for="GadoCadastro.Historico.Vacina" placeholder="Vacinas">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                        <button type="submit" class="btn btn-primary" value="GadoCadastro">Salvar mudanças</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    // Seleciona o campo de entrada de busca
    const searchInput = document.getElementById('searchInput');
    // Seleciona a tabela
    const table = document.getElementById('gadosTable');
    // Seleciona todas as linhas da tabela exceto a primeira (cabeçalho)
    const rows = table.querySelectorAll('tbody tr');

    // Adiciona um evento de input ao campo de busca
    searchInput.addEventListener('input', function () {
        const searchText = this.value.toLowerCase(); // Obtém o texto de pesquisa e converte para minúsculas

        // Itera sobre todas as linhas da tabela
        rows.forEach(row => {
            let display = false; // Define uma bandeira para controlar a visibilidade da linha


            // Itera sobre as células da linha atual, menos a última
            row.querySelectorAll('th').forEach(cell => {
                // Verifica se o texto de pesquisa está presente em alguma célula da linha
                if (cell.textContent.toLowerCase().includes(searchText) && !cell.textContent.toLowerCase().includes("Editar")) {
                    display = true; // Se encontrar, define a bandeira de exibição como verdadeira
                }
            });

            // Define a propriedade de estilo de exibição da linha com base na bandeira de exibição
            row.style.display = display ? '' : 'none';
        });
    });
</script>

Pages/Home.cshtml
@page
@model AgroConnect.Pages.HomeModel
@{
}
<style>
    .sidebar {
        min-height: 100vh;
    }

    .sidebar-icon {
        width: 20px;
        height: 20px;
        margin-right: 10px;
    }

    .main-content {
        padding: 20px;
    }
</style>
<!-- como centralizar uma div na metade da tela em bootstrap?-->
<div class="row" style="height: calc(100vh - 200px); overflow: hidden;">
    <div class="col-md-5 d-flex align-items-center justify-content-center flex-column flex-grow-1">
        <h1>Bem-vindo ao sistema agroconnect</h1>
        <h3>O que deseja fazer hoje?</h3>
        <div>
            <a asp-page="/Plantacoeshome"><button class="btn btn-primary px-5">Lavoura</button></a>
            <a asp-page="/GadoHome"><button class="btn btn-primary px-5">Gado</button></a>
            <a asp-page="/Deslogar"><button class="btn btn-primary px-5">Deslogar</button></a>
        </div>
    </div>
    <div class="col-md-7 d-flex align-items-center flex-grow-1">
        <object data="undraw_wind_turbine_x-2-k4.svg" type="image/svg+xml">
            <img src="~/images/undraw_wind_turbine_x-2-k4.svg" />
        </object>
    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container px-0 mx-0">
    <div class="row">
        <div class="col-md-8">
            <!-- Imagem responsiva -->
            <img src="~/images/undraw_environment_iaus.svg" alt="Trabalho de Manutenção" class="img-fluid">
        </div>
        <div class="col-md-4">
            <h1>Bem-vindo ao AgroConnect</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget libero fugiat, faucibus libero id, scelerisque quam.</p>
            <a href="#" class="btn btn-primary">Saiba Mais</a>
        </div>
    </div>
</div>

Pages/Login.cshtml
@page
@model AgroConnect.Pages.LoginModel
@{
}
<style>
    /* Estilos personalizados */
    .bg-image {
        background-image: url("~/images/LavouraSoja.jpg"); /* Substitua pelo caminho correto da imagem de fundo */
      background-size: cover;
      background-position: center;
      height: 100vh;
    }
    /* Estilos para o formulário */
    .form-container {
      background-color: rgba(255, 255, 255, 0.9);
      padding: 20px;
      border-radius: 10px;
    }
 </style>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                <div class="mb-3">
                    <label for="emailUsername" class="form-label">Email ou Nome de Usuário</label>
                    <input asp-for="UsuarioFront.Email" type="text" class="form-control" id="emailUsername">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Digite a Senha</label>
                    <input asp-for="UsuarioFront.Senha" type="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <a href="#" class="btn btn-link">Esqueceu a senha?</a>
                <button type="button" class="btn btn-danger">Login com Google</button>
            </form>
        </div>
        <div class="col-md-6 bg-image">
            <img src="~/images/LavouraSoja.jpg" alt="Imagem Agricultura" class="w-100 h-auto object-fit-fill">
        </div>
    </div>
    <div class="mt-3">
        <p>Primeira vez aqui? <a href="#" class="btn btn-link">Cadastre-se!</a></p>
    </div>
</div>

Pages/PlantacoesEditar.cshtml
@page
@model AgroConnect.Pages.PlantacoesEditarModel
@{
}